-- PROD.DS_MODEL.MOD_ROD_SPM_SETPOINT_RECOMMENDATION
-- Mirrors the production DDL so local runs match Snowflake column-for-column.

create or replace TABLE PROD.DS_MODEL.MOD_ROD_SPM_SETPOINT_RECOMMENDATION (
	TENANT_ID VARCHAR(16777216) NOT NULL,
	WELL_ID VARCHAR(16777216) NOT NULL,
	CONTROL_SYSTEM_ID VARCHAR(16777216) NOT NULL,
	CONTEXT VARCHAR(16777216) NOT NULL,
	EFFECTIVE_DATE TIMESTAMP_NTZ(9) NOT NULL,
	EFFECTIVE_ASPM_CLASSIFICATION VARCHAR(16777216),
	GAS_INTERFERENCE_SPEEDUP BOOLEAN,
	CURRENT_MIN_SPM_SETPOINT FLOAT,
	CURRENT_MAX_SPM_SETPOINT FLOAT,
	MIN_SAFE_SPM FLOAT,
	MAX_SAFE_SPM FLOAT,
	RECOMMENDED_MIN_SPM_SETPOINT FLOAT,
	RECOMMENDED_MAX_SPM_SETPOINT FLOAT,
	MIN_SPM_SETPOINT_CHANGED BOOLEAN,
	MAX_SPM_SETPOINT_CHANGED BOOLEAN,
	OPERATING_CLASSIFICATION VARCHAR(16777216),
	CREATED_ON TIMESTAMP_NTZ(9) NOT NULL DEFAULT CAST(CONVERT_TIMEZONE('UTC', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
	UPDATED_ON TIMESTAMP_NTZ(9) NOT NULL DEFAULT CAST(CONVERT_TIMEZONE('UTC', CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_TZ(9))) AS TIMESTAMP_NTZ(9)),
	MODEL_VERSION VARCHAR(16777216),
	MESSAGES VARCHAR(16777216),
	MINSOP_LOWER FLOAT,
	MINSOP_UPPER FLOAT,
	MAXSOP_LOWER FLOAT,
	MAXSOP_UPPER FLOAT,
	constraint PK_TENANT_WELL_ID_DATE primary key (TENANT_ID, WELL_ID, EFFECTIVE_DATE, UPDATED_ON)
)COMMENT='Add model_version field'
;
